### ISSUE TITLE
Error while building for Android or MacOs

### ISSUE THREAD

**Issue by VittorioParagallo** [adityapandey9/flutter-gun#9]
Hello,
at first congratulations for this library i'm sure a lot of devs were waiting for that.
I just tried the following snippet:

import 'package:flutter_gundb/flutter_gundb.dart';

void main() {
    final chainGunClient = FlutterGunSeaClient();
    
    final getAditya = gun.get('aditya');
    getAditya.put({
      name: "Aditya Kumar Pandey",
      email: "janatig@janatig.com",
    });
    getAditya.on((a, [b, c]) {
      print('Getting Value:: $a');
    });}

 it and in compiles for the web, while on other platforms i got the following errors:

- ANDROID
BUILD FAILED in 8m 15s
┌─ Flutter Fix ─────────────────────────────────────────────────────────────────────────────────┐
│ The plugin flutter_secure_storage requires a higher Android SDK version.                      │
│ Fix this issue by adding the following to the file                                            │
│ /Users/vittorioparagallo/AndroidStudioProjects/gundb_lab/gundb_lab/android/app/build.gradle:  │
│ android {                                                                                     │
│   defaultConfig {                                                                             │
│     minSdkVersion 18                                                                          │
│   }                                                                                           │
│ }                                                                                             │
│                                                                                               │
│ Following this change, your app will not be available to users running Android SDKs below 18. │
│ Consider searching for a version of this plugin that supports these lower versions of the     │
│ Android SDK instead.                                                                          │
│ For more information, see:                                                                    │
│ https://docs.flutter.dev/deployment/android#reviewing-the-gradle-build-configuration          │
└───────────────────────────────────────────────────────────────────────────────────────────────┘
Exception: Gradle task assembleDebug failed with exit code 1
Exited

- MacOS 
#16     new WebSocketGraphConnector
web_socket_graph_connector.dart:16
#17     FlutterGunClient.opt
flutter_gun_client.dart:63
#18     FlutterGunClient.initializedClient
flutter_gun_client.dart:51
#19     new FlutterGunSeaClient
flutter_gun_sea_client.dart:22
#20     main
main.dart:4
#21     _runMain.<anonymous closure> (dart:ui/hooks.dart:131:23)
#22     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:296:19)
#23     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: SocketException: Connection failed (OS Error: Operation not permitted, errno = 1), address = gun-manhattan.herokuapp.com, port = 443

**Comment by VittorioParagallo** [comment]
To get it working in macos:

The macOS build was giving a null key in the init file for the storage at line 26 because of luck of permissions required by flutter_secure_storage 8.0.0.  To configure them: 
Configure MacOS Version
You also need to add Keychain Sharing as capability to your macOS runner. To achieve this, please add the following in both your macos/Runner/DebugProfile.entitlements and macos/Runner/Release.entitlements (you need to change both files).
<key>keychain-access-groups</key>
<array/>
If you have set your application up to use App Groups then you will need to add the name of the App Group to the keychain-access-groups argument above. Failure to do so will result in values appearing to be written successfully but never actually being written at all. For example if your app has an App Group named "aoeu" then your value for above would instead read:
<key>keychain-access-groups</key>
<array>
	<string>$(AppIdentifierPrefix)aoeu</string>
</array>
If you are configuring this value through XCode then the string you set in the Keychain Sharing section would simply read "aoeu" with XCode appending the $(AppIdentifierPrefix) when it saves the configuration.

At this point you could get a message saying “Runner has entitlements that require signing with a development certificate. Enable development signing in the Signing & Capabilities editor. (in target 'Runner' from project 'Runner’)”

So you need to go to Xcode, type in the terminal
open macos/Runner.xcworkspace
Once  opened double click on Runner folder and click on “signing & capabilities” in the macOs section click on the button next to Signing Certificate “enable”. Then you have to choose the team just couple of fields before.  To choose you have just to login in your apple account.


Once this is set you can get this exception:

￼
UnsupportedError (Unsupported operation: package:webcrypto cannot be used from scripts or `flutter test` unless `flutter pub run webcrypto:setup` has been run for the current root project.)


vittorioparagallo@MBP-di-Vittorio gundb_lab % dart run webcrypto:setup
Building package executable... 
Built webcrypto:setup.
Building with assumed project root in:
/Users/vittorioparagallo/AndroidStudioProjects/gundb_lab/gundb_lab/
Using package:webcrypto from /Users/vittorioparagallo/.pub-cache/hosted/pub.dev/webcrypto-0.5.3
Generating build system with cmake
/bin/sh: cmake: command not found
Generating with cmake failed, ensure you have dependencies!


brew install cmake

- But then 
vittorioparagallo@MBP-di-Vittorio gundb_lab % dart run webcrypto:setup
Building package executable... 
Built webcrypto:setup.
Building with assumed project root in:
/Users/vittorioparagallo/AndroidStudioProjects/gundb_lab/gundb_lab/
Using package:webcrypto from /Users/vittorioparagallo/.pub-cache/hosted/pub.dev/webcrypto-0.5.3
Generating build system with cmake
CMake Error: The source directory "/Users/vittorioparagallo/.pub-cache/hosted/pub.dev/src" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
Generating with cmake failed, ensure you have dependencies!

It seems a bug of webcrypto as stated at https://github.com/google/webcrypto.dart/issues/20

Since actual gundb version uses webcrypto: ^0.5.3, To fix the bug it go to, depending on where it has been downloaded:
~/.pub-cache/hosted/[pub.dartlang.org/webcrypto-0.5.3/bin/setup.dart](http://pub.dartlang.org/webcrypto-0.5.3/bin/setup.dart) or 
~/.pub-cache/hosted/pub.dev/webcrypto-0.5.3/bin/setup.dart 
And correct line 66
 From webcryptoRoot.resolve('src’)
 To webcryptoRoot.resolve('webcrypto-0.5.3/src')

**Comment by adityapandey9** [comment]
Hi @VittorioParagallo Thank you for the issue, I will. It looks like the flutter storage has some permission problem. It looks like I am using an older version of this package. I will update and try to recreate the issue.
